name: Check and build

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    name: Check all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Check Rust formatting
        run: |
          nix develop --command \
            cargo fmt --check

  build_and_test:
    name: Test and build
    needs: check
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: nix flake check 

      - name: Build
        run: nix build .#advent-of-code

      - name: Docker image
        run: nix build .#docker
