name: Check and build

on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    name: Check all
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true

      - name: Check Rust formatting
        run: |
          nix develop --command \
            cargo fmt --check
      - name: Audit Rust code
        run: |
          nix develop --command \
            cargo-deny check

  build_and_test:
    name: Test and build
    needs: check
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Set up Rust cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: aoc-${{ hashFiles('**/Cargo.lock') }}
      - name: Test
        run: |
          nix develop --command \
            cargo test

      - name: Build
        run: nix build .#advent-of-code

      - name: Docker image
        run: nix build .#docker
